import { escapeHTML as e, publicCard } from './domain.js';
export function profileHTML(card, source, privacyURL) {
  const c=publicCard(card), id=e(c.id), src=e(source);
  const links=[['website','Website'],['portfolio','Portfolio'],['booking','Book a meeting'],['cv','View CV']].filter(([key])=>c[key]);
  const actionKey={'Website':'website','Portfolio':'portfolio','Book a meeting':'booking','View CV':'cv'}[c.primaryAction];
  const action=actionKey && c[actionKey] ? `<a class="primary" href="/p/${id}/go/${actionKey}?source=${src}">${e(c.primaryActionLabel || c.primaryAction)} ↗</a>` : '';
  const contact=`<div class="links">${c.email?`<a href="mailto:${e(c.email)}">Email</a>`:''}${c.phone?`<a href="tel:${e(c.phone.replace(/[^+\d]/g,''))}">Call</a>`:''}</div>`;
  const sections={About:`<p class="bio">${e(c.bio)}</p>`, Contact:contact, Links:`<div class="links">${links.map(([k,label])=>`<a href="/p/${id}/go/${k}?source=${src}" rel="noopener noreferrer">${label} ↗</a>`).join('')}${(c.socials||[]).map(l=>`<a href="${e(l.url)}" rel="noopener noreferrer">${e(l.service)} ↗</a>`).join('')}</div>`};
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${e(c.name)} · TapLead</title><link rel="stylesheet" href="/assets/profile.css"><link rel="stylesheet" href="/p/${id}/theme.css"></head><body><main><a class="wordmark" href="/">▣ TapLead<span>Tap. Connect. Convert.</span></a><article><div class="cover"><span>${e(c.persona)}</span><b>Every introduction.<br>A new possibility.</b></div><div class="identity"><div class="avatar" aria-hidden="true">${e(c.name.split(' ').map(p=>p[0]).slice(0,2).join(''))}</div><h1>${e(c.preferredName||c.name)}</h1><p>${e(c.title)}${c.company?' · '+e(c.company):''}</p><p class="headline">${e(c.headline)}</p>${c.location?`<p class="muted">${e(c.location)}</p>`:''}<a class="primary" href="/p/${id}/contact.vcf?source=${src}">Save Contact ↓</a>${action}${c.sectionOrder.map(k=>sections[k]).join('')}<details><summary>Share your details ↗</summary><p class="muted">Introduce yourself to ${e(c.preferredName||c.name)}. Your details are shared only when you submit this form.</p><form method="post" action="/p/${id}/leads"><input type="hidden" name="source" value="${src}"><label>Name<input name="name" required maxlength="120" autocomplete="name"></label><label>Email<input name="email" type="email" maxlength="254" autocomplete="email"></label><label>Phone<input name="phone" type="tel" maxlength="60" autocomplete="tel"></label><label>Company<input name="company" maxlength="120" autocomplete="organization"></label><label>Role<input name="role" maxlength="120" autocomplete="organization-title"></label><label>Interested in<input name="interest" maxlength="500"></label><label>Message<textarea name="message" maxlength="2000" rows="3"></textarea></label><label class="trap" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><label class="consent"><input type="checkbox" name="consent" value="true" required>I agree to share these details with ${e(c.name)} so they can contact me about my enquiry.</label><p class="muted">Please provide an email address or phone number.</p><button class="primary">Share my details</button></form></details></div></article><footer>${privacyURL?`<a href="${e(privacyURL)}">Privacy</a> · `:''}Powered by TapLead<br>Anonymous visits do not identify you.</footer></main></body></html>`;
}
export function messageHTML(title,message) { return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} · TapLead</title><link rel="stylesheet" href="/assets/profile.css"></head><body><main><article class="identity"><h1>${e(title)}</h1><p>${e(message)}</p><a href="/" class="back">TapLead home</a></article></main></body></html>`; }
